#!/bin/bash
declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed
declare _build=""

if [[ "$SHIP" == "true" ]]; then
	_build="_ship";
fi

sudo $_fastboot $* \
flash bootloader $_tot_image_path/bootloader${_build}.img \
reboot-bootloader

sleep 2s
