#!/bin/bash
declare _all_pt=/tmp/all_pt.zip
declare _fastboot=TOT/tools/bin/fastboot
declare _tot_image_path=TOT/vendor_htc_flounder
declare _test_image_path=test/signed
declare _dashboard_pdk=TOT/dashboard/AOSP/*

sudo $_fastboot $* \
-w \
flash boot $_dashboard_pdk/boot.img \
flash recovery $_dashboard_pdk/recovery.img \
flash system $_dashboard_pdk/system.img \
flash vendor $_dashboard_pdk/vendor.img \
reboot

sleep 2s
