#!/bin/bash
declare _all_pt=/tmp/all_pt.zip
declare _fastboot=TOT/tools/bin/fastboot
declare _tot_image_path=TOT/vendor_htc_flounder
declare _test_image_path=test/signed

rm -f $_all_pt; zip -j9 $_all_pt $_tot_image_path/pt_*

sudo $_fastboot $* \
flash bct $_tot_image_path/rawbct.img \
flash hboot $_tot_image_path/hboot.img \
flash nvtboot $_tot_image_path/nvtboot.img \
flash nvtbootwb0 $_tot_image_path/nvtbootwb0.bin \
flash tos $_tot_image_path/tos.img \
flash mts_preboot_prod $_tot_image_path/mts_preboot_prod \
flash mts_prod $_tot_image_path/mts_prod \
flash gp1 $_tot_image_path/gp1.img \
flash zip $_all_pt \
reboot-bootloader

sleep 2s
