#!/bin/bash
declare _all_pt=/tmp/all_pt.zip
declare _fastboot=TOT/tools/bin/fastboot
declare _tot_image_path=TOT/vendor_htc_flounder
declare _test_image_path=test/signed
declare _dogfood=TOT/DogFood/*

sudo $_fastboot $* \
-w \
flash boot $_dogfood/boot.img \
flash recovery $_dogfood/recovery.img \
flash system $_dogfood/system.img \
flash vendor $_dogfood/vendor.img \
reboot

sleep 2s
