#!/bin/bash
#Step 4: Using the new bootloader, reflash all the TOT bootloader images in vendor/htc/flounder, as well as TOT Android again

#(Finally, this test is to make sure the new bootloader can flash *different* bootloader images and make sure the BCT update mechanism is correct. Go to vendor/htc/flounder and flash all the previous version bootloaders again. If mts_preboot_prod/mts_prod images )

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed
declare _build=""

if [[ "$SHIP" == "true" ]]; then
	_build="_ship";
fi

sudo $_fastboot $* \
flash bootloader $_tot_image_path/bootloader${_build}.img

. 2-2_flash_google_dogfood $*
