#!/bin/bash
( cd ../TOT/vendor_htc_flounder
  _h=$(git log -1 --format=%h)
  cp bootloader.img /tmp/bootloader_orig.img
  . copy
  git commit -a -m "Hboot version: 3.x.0.2100"
  ./mkimg.py
  cp bootloader.img /tmp/bootloader_new.img
  for((i=1; i<=10; ++i)); do
	echo "##### Test $i"
	sudo ../tools/bin/fastboot $* flash bootloader /tmp/bootloader_orig.img reboot-bootloader
	sleep 2s
	sudo ../tools/bin/fastboot $* flash bootloader /tmp/bootloader_new.img reboot-bootloader
	sleep 2s
  done;
  echo "Test done."
  git reset --hard $_h
 )
