#!/bin/bash
if [[ "$COUNT" != "" ]]; then
	_count=$COUNT;
else
	_count=10;
fi

( cd ../TOT/vendor_htc_flounder
  _h=$(git log -1 --format=%h)
  git reset --hard ohd/l-dev-pdk-flounder
  cp bootloader.img /tmp/bootloader_orig.img
  rm -f hboot* rawbct*
  . copy
  git commit -a -m "Hboot version: 3.99.0"
  ./mkimg.py
  cp bootloader.img /tmp/bootloader_new.img
  git reset --hard $_h
  for((i=1; i<=_count; ++i)); do
	echo "##### Test $i/$_count ####"
	sudo ../tools/bin/fastboot $* oem battinfo
	sudo ../tools/bin/fastboot $* flash mts_prod ../tools/bin/fastboot
	sudo ../tools/bin/fastboot $* flash bootloader /tmp/bootloader_orig.img reboot-bootloader
	sleep 2s
	sudo ../tools/bin/fastboot $* flash mts_prod ../tools/bin/fastboot
	sudo ../tools/bin/fastboot $* flash bootloader /tmp/bootloader_new.img reboot-bootloader
	sleep 2s
  done;
  echo "Test done."
 )
