#!/bin/bash

_download_dir=~/Downloads
_dest_dir=dashboard_hboot_build
_tot_vendor=../../TOT/vendor_htc_flounder

_cl=$1
_ship=$(ls $_download_dir/${_cl}_T1_Generic_WWE_K44_*_GEP_SHIP_64bits_hboot_java7.zip 2>/dev/null)
_eng=$(ls $_download_dir/${_cl}_T1_Generic_WWE_K44_*_GEP{,_ENG}_64bits_hboot_java7.zip 2>/dev/null)

if [[ "$_cl" -ne 0 ]]; then
	rm -rf $_dest_dir/*
	unzip -o $_ship -d $_dest_dir/ hboot.img *.log
	mv $_dest_dir/hboot.img $_dest_dir/hboot_ship.img
	unzip -o $_eng -d $_dest_dir/ hboot.img nvtboot.img nvtbootwb0.bin *.log
	mv $_dest_dir/hboot.img $_dest_dir/hboot_eng.img
fi

file_list="mts_prod mts_preboot_prod rawbct.img hboot.img nvtboot.img nvtbootwb0.bin tos.img"

# Process TOT
_log=$(git --git-dir=$_tot_vendor/.git --work-tree=$_tot_vendor log --oneline -1 -- bootloader.img)
echo "TOT: $_log" > info.txt
_eng_bootloader="$_tot_vendor/bootloader_eng.img"
_ship_bootloader="$_tot_vendor/bootloader.img"
for i in eng ship; do
	echo "  $(eval md5sum \${_${i}_bootloader} | cut -d " " -f 1) $(eval basename \${_${i}_bootloader})" >> info.txt
	eval unzip -o \${_${i}_bootloader} $file_list
	mv -fv rawbct{,_$i}.img
	mv -fv hboot{,_$i}.img
done
echo "HBoot: $_cl" >> info.txt
for i in $_dest_dir/{hboot_*.img,nvtboot.img,nvtbootwb0.bin}; do
	_md5=$(md5sum $i | cut -d " " -f 1)
	chmod 644 $i
	cp -fv $i .
	echo "  $_md5 $(basename $i)" >> info.txt
done

git add .
git commit -a -m "$2

$(cat info.txt)"
