#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _adb=../TOT/tools/bin/adb
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed

dprint()
{
	_msg="$*"
	printf "$(date +'%F %R'): "
	printf "$_msg"
}

dprint "Please make sure the DUT is UNLOCKED, then press enter to continue..."; read

dprint "Flashing volantis bootloaders@TOT...\n"
SHIP=true . 1-6_flash_TOT_bl_images $*
dprint "Flashing volantis pdk@TOT...\n"
. 1-7_flash_google_dogfood $*
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the box on screen to authenticate your adb host, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s

dprint "Flashing volantis testing bootloaders...\n"
SHIP=true . 2-1_flash_new_signed_bl_images $*
. 2-2_flash_google_dogfood $*
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the box on screen to authenticate your adb host, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s

dprint "Flashing volantis pdk@TOT with testing bootloaders...\n"
SHIP=true . 2-3_flash_new_bl_and_dogfood $*
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the box on screen to authenticate your adb host, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s

dprint "Locking the testing bootloader...\n"
sudo $_fastboot $* oem lock
dprint "Wait for device back to fastboot, then press enter to continue..."; read
sudo $_fastboot $* reboot
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the unlock-ability and adb debugging boxed in the dev-options menu screen, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s

dprint "Unlocking the testing bootloader..\n"
sudo $_fastboot $* oem unlock
dprint "Wait for device back to fastboot, then press enter to continue..."; read
sudo $_fastboot $* reboot
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the box on screen to authenticate your adb host, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s

dprint "Flashing volantis pdk@TOT with bootloaders@TOT...\n"
SHIP=$SHIP . 2-4_flash_TOT_bl_and_dogfood $*
sleep 2s
dprint "Wait for device boot up, then press enter to continue..."; read
sudo $_adb devices
dprint "Check the box on screen to authenticate your adb host, then press enter to continue..."; read
sudo $_adb $* reboot-bootloader
sleep 2s
dprint "Starting upgrade/downgrade test...\n"
. 2-5_upgrade_downgrade_bootloader_img $*
