#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _adb=../TOT/tools/bin/adb
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed

dprint()
{
	_msg="$*"
	printf "$(date +'%F %R'): "
	printf "$_msg"
}


wait_for_boot_completed()
{
	while ! ( sudo $_adb $* wait-for-device logcat -d | grep -m 1 'android.intent.action.BOOT_COMPLETED' ); do
		dprint "Waiting for device boot up...\n";
		sleep 10s
	done
}

wait_for_boot_completed_and_reboot()
{
	wait_for_boot_completed $*
	adb_reboot_bootloader $*
}

wait_for_boot_completed_and_unlock()
{
	wait_for_boot_completed $*
	adb_unlock_ability $*
}

adb_reboot_bootloader()
{
	dprint "Rebooting...\n";
	sudo $_adb $* reboot-bootloader
	sleep 2s
}

adb_unlock_ability()
{
	local part_name="PST"
	local pst_path="/dev/block/platform/sdhci-tegra.3/by-name/$part_name"
	local tmp="/tmp"
	sudo $_adb $* pull $pst_path $tmp
	xxd -c 1 -s -1 $tmp/$part_name | sed -r "s/: 00/: 01/g" | xxd -c 1 -r > $tmp/${part_name}_1
	sudo $_adb $* push $tmp/${part_name}_1 /data
	sudo $_adb $* shell dd if=/data/${part_name}_1 of=$pst_path
	sudo $_adb $* reboot-bootloader
	sleep 2s
}

dprint "Please make sure the DUT is UNLOCKED, then press enter to continue..."; read

dprint "Flashing volantis bootloaders@TOT...\n"
SHIP=true . 1-6_flash_TOT_bl_images $*
dprint "Flashing volantis pdk@TOT...\n"
. 1-7_flash_google_dogfood $*
sleep 2s
wait_for_boot_completed_and_reboot $*

dprint "Flashing volantis testing bootloaders...\n"
SHIP=true . 2-1_flash_new_signed_bl_images $*
. 2-2_flash_google_dogfood $*
sleep 2s
wait_for_boot_completed_and_reboot $*

dprint "Flashing volantis pdk@TOT with testing bootloaders...\n"
SHIP=true . 2-3_flash_new_bl_and_dogfood $*
sleep 2s
wait_for_boot_completed_and_reboot $*

dprint "Locking the testing bootloader...\n"
sudo $_fastboot $* oem lock
sleep 20s
dprint "Wait for device back to fastboot....\n";
sudo $_fastboot $* reboot
sleep 2s
dprint "Wait for device boot up...";
wait_for_boot_completed_and_unlock $*

dprint "Unlocking the testing bootloader..\n"
sudo $_fastboot $* oem unlock
sleep 20s
dprint "Wait for device back to fastboot....\n";
sudo $_fastboot $* reboot
sleep 2s
dprint "Wait for device boot up...";
wait_for_boot_completed_and_reboot $*
sleep 2s

dprint "Flashing volantis pdk@TOT with bootloaders@TOT...\n"
SHIP=true . 1-6_flash_TOT_bl_images $*
SHIP=true . 2-1_flash_new_signed_bl_images $*
SHIP=true . 2-4_flash_TOT_bl_and_dogfood $*
sleep 2s
wait_for_boot_completed_and_reboot $*

dprint "Flashing testing bootloader...\n"
SHIP=true . 2-1_flash_new_signed_bl_images $*
sleep 2s
sudo ../TOT/tools/bin/htc_fastboot $* flash zip ../test/largezip/0P82IMG_T1* && \
sudo ../TOT/tools/bin/htc_fastboot $* flash zip ../test/largezip/0P82IMG-BOOT_T1* && \
sudo ../TOT/tools/bin/htc_fastboot $* reboot
sleep 2s
wait_for_boot_completed_and_reboot $*

dprint "Starting upgrade/downgrade test...\n"
SHIP=true . 2-5_upgrade_downgrade_bootloader_img $*
