#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=TOT/tools/bin/fastboot
declare _adb=TOT/tools/bin/adb
declare _tot_image_path=TOT/vendor_htc_flounder
declare _test_image_path=test/signed

dprint()
{
	_msg="$*"
	printf "$(date +'%F %R'): "
	printf "$_msg"
}

dprint "Backup MFG and BIF, then recover pre-bootloaders to ToT...\n"
( cd nvflash_0212;
sudo ../$_tot_image_path/nvflash \
--read EKS /tmp/eks.bin \
--read MFG /tmp/mfg.bin \
--read BIF /tmp/bif.bin \
--bl ../$_tot_image_path/hboot.img \
--preboot ../$_tot_image_path/mts_preboot_prod \
--bootpack ../$_tot_image_path/mts_prod \
--applet ../$_tot_image_path/nvtboot.img \
--go \
&& \
sudo ../$_tot_image_path/nvflash --resume \
--bct Volantis64_Elpida_2GB_EDFA164A2MA_JD_F_792MHz.cfg \
--setbct \
--odmdata 0x80000 \
--configfile flash_16g.cfg \
--dtbfile tegra132-flounder64.dtb \
--create \
--bl ../$_tot_image_path/hboot.img \
--preboot ../$_tot_image_path/mts_preboot_prod \
--bootpack ../$_tot_image_path/mts_prod \
--applet ../$_tot_image_path/nvtboot.img \
--go; \
)

dprint "Long-press-reboot the device to 'force-recovery' mode and press enter to continue..."; read
dprint "Recover bootloaders to 2/12 release via nvflash...\n"
sleep 2s

( cd nvflash_0212; \
sudo ./nvflash \
--bct Volantis64_Elpida_2GB_EDFA164A2MA_JD_F_792MHz.cfg \
--setbct \
--odmdata 0x80000 \
--configfile flash_16g.cfg \
--dtbfile tegra132-flounder64.dtb \
--create \
--bl ./hboot.img \
--preboot ./mts_preboot_prod \
--bootpack ./mts_prod \
--go
)

sleep 2s
dprint "Sometimes the device hit reboot fail, if so, long-press-reboot the device first.\nPress enter to continue..."; read
dprint "Recover HBoot to 3.18 release via fastboot...\n"
sudo $_fastboot flash hboot hboot_3.18/hboot.img reboot-bootloader
sleep 2s

dprint "Sometimes the device hit reboot fail, if so, long-press-reboot the device first.\nPress enter to continue..."; read
dprint "Recover HBoot to 3.19 release via fastboot...\n"

sudo $_fastboot $* \
flash bct bootloaders_3.19/rawbct.img \
flash hboot bootloaders_3.19/hboot.img \
flash nvtboot bootloaders_3.19/nvtboot.img \
flash nvtbootwb0 bootloaders_3.19/nvtbootwb0.bin \
flash tos bootloaders_3.19/tos.img \
flash mts_preboot_prod bootloaders_3.19/mts_preboot_prod \
flash mts_prod bootloaders_3.19/mts_prod \
flash gp1 bootloaders_3.19/gp1.img \
flash eks /tmp/eks.bin \
flash zip bootloaders_3.19/all_pt.zip \
reboot-bootloader
sleep 2s

dprint "Recover HBoot to 3.22 release via fastboot...\n"
sudo $_fastboot flash hboot bootloaders_3.22/hboot.img flash nvtboot bootloaders_3.22/nvtboot.img reboot-bootloader
sleep 2s
sudo $_fastboot $* \
flash bct bootloaders_3.22/rawbct.img \
flash hboot bootloaders_3.22/hboot.img \
flash nvtboot bootloaders_3.22/nvtboot.img \
flash nvtbootwb0 bootloaders_3.22/nvtbootwb0.bin \
flash tos bootloaders_3.22/tos.img \
flash mts_preboot_prod bootloaders_3.22/mts_preboot_prod \
flash mts_prod bootloaders_3.22/mts_prod \
flash gp1 bootloaders_3.22/gp1.img \
flash eks /tmp/eks.bin \
flash zip bootloaders_3.22/all_pt.zip \
reboot-bootloader
sleep 2s

. 1-6_flash_TOT_bl_images $*
