#!/bin/bash

declare i=0;
declare count=$1;
declare id=$2;
declare ret=-1;
shift 2

dprint()
{
	_msg="$*"
	printf "$(date +'%F %R'): "
	printf "$_msg"
}

for((i=1; i<=count; ++i)); do
	dprint "### $i/$count ##\n";
	ret=-1;
	sudo TOT/tools/bin/fastboot -s $id oem battinfo
	time $* || break;
	sudo TOT/tools/bin/fastboot -s $id reboot-bootloader
	sleep 2s;
	. 2-1_flash_new_signed_bl_images -s $id
	ret=0;
done;

test $ret -eq 0 && dprint "SUCCESS\n" || dprint "FAIL\n"
