#!/bin/bash

declare _largezip_path=../test/largezip
declare _bigsystem_path=../test/bigsystem
declare _adb=../TOT/tools/bin/adb

sudo $_adb kill-server
sudo $_adb devices

wait_to_bootup()
{
	sleep 10s;
	echo -n "Waiting for device booting up..." >&2
	sudo $_adb $* wait-for-device root && sleep 2s
	echo " Done." >&2
}

get_partition_md5()
{
	sleep 5s;
	echo -n "Counting MD5 of system partition..." >&2
	sudo $_adb $* wait-for-device shell md5 /dev/block/platform/sdhci-tegra.3/by-name/APP 2>&1
	sleep 2s;
	echo " Done." >&2
}

declare res1=""
declare res2=""

sudo ../TOT/tools/bin/fastboot $* -w
sleep 1s;
sudo ../TOT/tools/bin/fastboot $* \
	flash system $_bigsystem_path/system.img \
	flash boot $_bigsystem_path/boot.img \
	flash recovery $_bigsystem_path/recovery.img \
	flash vendor $_bigsystem_path/vendor.img \
	flash cache $_bigsystem_path/cache.img \
	reboot
wait_to_bootup $* && res1=$(get_partition_md5 $*) || res1="FAIL"
echo "Bigsystem md5:"
echo "$res1";

sudo $_adb $* reboot-bootloader
sleep 5s;
sudo ../TOT/tools/bin/fastboot $* -w
sudo ~/bin/htc_fastboot $* flash zip $_largezip_path/0P82IMG_*.zip
sudo ~/bin/htc_fastboot $* flash zip $_largezip_path/0P82IMG-*.zip
sudo ~/bin/htc_fastboot $* reboot
wait_to_bootup $* && res2=$(get_partition_md5 $*) || res2="FAIL"

echo "$res1"
echo "$res2"
if [[ "$res1" != "FAIL" ]] && [[ "$res2" != "FAIL" ]] && [[ "$res1" == "$res2" ]]; then echo "SUCCESS"; else echo "FAIL"; fi
