#!/bin/bash

declare _largezip_path=../test/largezip
declare _bigsystem_path=../test/bigsystem

wait_to_bootup()
{
	sleep 10s;
	adb $* wait-for-device root && sleep 2s
}

get_partition_md5()
{
	adb $* wait-for-device shell md5 /dev/block/platform/sdhci-tegra.3/by-name/APP /dev/block/platform/sdhci-tegra.3/by-name/VNR
}

declare res1=""
declare res2=""

sudo ../TOT/tools/fastboot $* -w
sleep 1s;
sudo ../TOT/tools/fastboot $* \
	flash system $_bigsystem_path/system.img \
	flash boot $_bigsystem_path/boot.img \
	flash recovery $_bigsystem_path/recovery.img \
	flash vendor $_bigsystem_path/vendor.img \
	flash cache $_bigsystem_path/cache.img \
	reboot
wait_to_bootup && res1=$(get_partition_md5) || res1="FAIL"

adb $* reboot-bootloader
sleep 5s;
sudo ../TOT/tools/fastboot $* -w
sudo ~/bin/htc_fastboot $* flash zip $_largezip_path/rom.img
sudo ~/bin/htc_fastboot $* reboot
wait_to_bootup && res2=$(get_partition_md5) || res2="FAIL"

echo "$res1"
echo "$res2"
if [[ "$res1" != "FAIL" ]] && [[ "$res2" != "FAIL" ]] && [[ "$res1" == "$res2" ]]; then echo "SUCCESS"; else echo "FAIL"; fi
