#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _adb=../TOT/tools/bin/adb
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed

dprint()
{
	_msg="$*"
	printf "$(date +'%F %R'): "
	printf "$_msg"
}

. 2-1_flash_new_signed_bl_images $*
sleep 2s;
sudo $_fastboot $* oem reboot_nvflash
sleep 2s;

dprint "Backup EKS, MFG, and BIF, then recover pre-bootloaders to ToT...\n"

( cd $_tot_image_path;

  touch system.img vendor.img boot.img recovery.img; cp hboot_eng.img hboot.img;

  sudo ./nvflash \
  --read EKS /tmp/eks.bin \
  --read BIF /tmp/bif.bin \
  --read MFG /tmp/mfg.bin \
  --bl ../$_test_image_path/hboot_eng.img \
  --preboot ../$_test_image_path/mts_preboot_prod \
  --bootpack ../$_test_image_path/mts_prod \
  --applet ../$_test_image_path/nvtboot.img \
&& \
  sudo ./nvflash --resume \
  --bct Volantis64_924MHz_DRAM_BCT_20140605.cfg \
  --setbct --odmdata 0x80000 \
  --configfile flash_16g.cfg --create \
  --bl ../$_test_image_path/hboot_eng.img \
  --preboot ../$_test_image_path/mts_preboot_prod \
  --bootpack ../$_test_image_path/mts_prod \
  --applet ../$_test_image_path/nvtboot.img \
&& \
  sudo ./nvflash --resume \
  --download MFG /tmp/mfg.bin \
  --download EKS /tmp/eks.bin \
  --download BIF /tmp/bif.bin \
  --download EBT ../../test/signed/hboot_eng.img \
  --download NVC ../../test/signed/nvtboot.img \
  --format_partition LNX \
  --bl ../$_test_image_path/hboot_eng.img \
  --preboot ../$_test_image_path/mts_preboot_prod \
  --bootpack ../$_test_image_path/mts_prod \
  --applet ../$_test_image_path/nvtboot.img --go \

  rm -f system.img vendor.img boot.img recovery.img hboot.img;
)

sleep 2s;
. 2-1_flash_new_signed_bl_images $*
