#!/bin/bash

declare _fastboot=../TOT/tools/bin/fastboot
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _bct_file=""

if [[ -f "$_tot_image_path/$1" ]]; then
	_bct_file="$1";
	shift 1;
else
	_bct_file="Volantis64_924MHz_DRAM_BCT_20140605.cfg";
fi

echo "Assigned bct file: $_bct_file"

( cd $_tot_image_path; \
rm -f system.img vendor.img boot.img recovery.img /tmp/mfg.bin;
touch system.img vendor.img boot.img recovery.img /tmp/mfg.bin;
cp -fv hboot_eng.img hboot.img;
cp -fv board_info.bin /tmp/bif.bin;
cp -fv eks.dat /tmp/eks.bin;
sudo ./nvflash \
--bct $_bct_file \
--setbct \
--odmdata 0x80000 \
--configfile flash_16g.cfg \
--create \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
&& \
sudo ./nvflash --resume \
--download MFG /tmp/mfg.bin \
--download EKS /tmp/eks.bin \
--download BIF /tmp/bif.bin \
--download EBT hboot_eng.img \
--format_partition LNX \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
--go;
rm -f system.img vendor.img boot.img recovery.img /tmp/mfg.bin;
)

sleep 2s
sudo $_fastboot devices
if [[ "$_update_pt" != "false" ]]; then
	. 1-6_flash_TOT_bl_images $*
fi
