#!/bin/bash

declare _fastboot=../TOT/tools/bin/fastboot
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _bct_file=""

if [[ -f "$_tot_image_path/$1" ]]; then
	_bct_file="$1";
	shift 1;
else
	_bct_file="Volantis64_924MHz_DRAM_BCT_20140605.cfg";
fi

echo "Assigned bct file: $_bct_file"

( cd $_tot_image_path; \
sudo ./nvflash \
--read EKS /tmp/eks.bin \
--read MFG /tmp/mfg.bin \
--read BIF /tmp/bif.bin \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
&& \
sudo ./nvflash --resume \
--bct $_bct_file \
--setbct \
--odmdata 0x80000 \
--configfile flash_16g.cfg \
--create \
--skip_part APP \
--skip_part LNX \
--skip_part SOS \
--skip_part VNR \
--skip_part EKS \
--skip_part MFG \
--skip_part BIF \
--skip_part EBT \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
&& \
sudo ./nvflash --resume \
--download MFG /tmp/mfg.bin \
--download EKS /tmp/eks.bin \
--download BIF /tmp/bif.bin \
--download EBT hboot_eng.img \
--format_partition LNX \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
--go;
)

sleep 2s
sudo $_fastboot devices
if [[ "$_update_pt" != "false" ]]; then
	. 1-6_flash_TOT_bl_images $*
fi
