#!/bin/bash

declare _fastboot=../TOT/tools/bin/fastboot
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../recover_fused

( cd $_test_image_path; \
  sudo rm -f system.img vendor.img boot.img recovery.img /tmp/mfg.bin;
  touch system.img vendor.img boot.img recovery.img /tmp/mfg.bin;
  sudo cp -fv board_info.bin /tmp/bif.bin;
  sudo cp -fv eks.dat /tmp/eks.bin;
  sudo ./nvflash \
	--blob blob.bin \
	--bct s_recover_rawbct.bct \
	--setbct \
	--odmdata 0x80000 \
	--configfile flash_16g_s_recover.cfg \
	--create \
	--applet s_recover_nvtboot.img \
	--bootpack mts_prod \
	--preboot mts_preboot_prod \
	--bl s_recover_hboot.img \
	--go;
  sudo rm -f system.img vendor.img boot.img recovery.img /tmp/mfg.bin /tmp/bif.bin /tmp/eks.bin
)

sleep 2s
#sudo $_fastboot devices
#. 1-6_flash_TOT_bl_images $*
#. 1-6_flash_TOT_bl_images $*
