#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=TOT/tools/bin/fastboot
declare _adb=TOT/tools/bin/adb
declare _tot_image_path=TOT/vendor_htc_flounder
declare _test_image_path=recover_fused

( cd $_test_image_path; \
  sudo ./nvflash \
	--blob blob.bin \
	--bct s_recover_rawbct.bct \
	--read EKS /tmp/eks.bin \
	--read BIF /tmp/bif.bin \
	--read MFG /tmp/mfg.bin \
	--applet s_recover_nvtboot.img \
	--bootpack mts_prod \
	--preboot mts_preboot_prod \
	--bl s_recover_hboot.img \
	--go \
&& \
  sudo ./nvflash --resume \
	--bct s_recover_rawbct.bct \
	--setbct \
	--odmdata 0x80000 \
	--configfile flash_16g_s_recover.cfg \
	--create \
	--applet s_recover_nvtboot.img \
	--bootpack mts_prod \
	--preboot mts_preboot_prod \
	--bl s_recover_hboot.img \
	--go \
)

sleep 2s
sudo $_fastboot devices
. 1-6_flash_TOT_bl_images $*
. 1-6_flash_TOT_bl_images $*
