#!/bin/bash

declare _all_pt=/tmp/all_pt.zip
declare _fastboot=../TOT/tools/bin/fastboot
declare _adb=../TOT/tools/bin/adb
declare _tot_image_path=../TOT/vendor_htc_flounder
declare _test_image_path=../test/signed

( cd $_tot_image_path; \
sudo ./nvflash \
--read EKS /tmp/eks.bin \
--read MFG /tmp/mfg.bin \
--read BIF /tmp/bif.bin \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
&& \
sudo ./nvflash --resume \
--bct Volantis64_924MHz_DRAM_BCT_20140605.cfg \
--setbct \
--odmdata 0x80000 \
--configfile flash_16g.cfg \
--create \
--skip_part APP \
--skip_part LNX \
--skip_part SOS \
--skip_part VNR \
--skip_part EKS \
--skip_part MFG \
--skip_part BIF \
--skip_part EBT \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
&& \
sudo ./nvflash --resume \
--download MFG /tmp/mfg.bin \
--download EKS /tmp/eks.bin \
--download BIF /tmp/bif.bin \
--download EBT hboot_eng.img \
--bl hboot_eng.img \
--preboot mts_preboot_prod \
--bootpack mts_prod \
--applet nvtboot.img \
--go;
)

sleep 2s
sudo $_fastboot devices
. 1-6_flash_TOT_bl_images $*
